Repository ynput/ayon-nuke, pull requests merged in 2025-03, with the labels that each got.

#85 Add custom node classes and change subset to product
  client/ayon_nuke/api/lib.py
  client/ayon_nuke/startup/custom_write_node.py
  server/settings/imageio.py
Labels: type: bug, sponsored

#81 AY-7442 Dissociate file_type and ext knob computation (SXR and JPG extension support).
  client/ayon_nuke/api/lib.py
  client/ayon_nuke/api/plugin.py
  client/ayon_nuke/plugins/publish/collect_writes.py
  client/ayon_nuke/plugins/publish/extract_render_local.py
  client/ayon_nuke/plugins/publish/validate_write_nodes.py
  client/ayon_nuke/startup/custom_write_node.py
Labels: type: enhancement, sponsored

#88 add settings conversion for #85
  client/ayon_nuke/api/lib.py
  client/ayon_nuke/startup/custom_write_node.py
  server/settings/conversion.py
  server/settings/imageio.py
Labels: type: enhancement

#89 Remove deprecated ExtractReviewDataLut
  client/ayon_nuke/plugins/publish/extract_review_data_lut.py
  server/settings/publish_plugins.py
Labels: type: enhancement, community

#83 Settings: Improve docstrings / clarity of settings
  server/settings/create_plugins.py
  server/settings/dirmap.py
  server/settings/imageio.py
  server/settings/publish_plugins.py
Labels: type: enhancement, community

#90 Do not collect 'version' to script data and not to `context.data`
  client/ayon_nuke/plugins/publish/collect_context_data.py
Labels: type: enhancement, community

#80 AY-7475 - Define default render targets through settings.
  client/ayon_nuke/api/plugin.py
  server/settings/create_plugins.py
Labels: type: enhancement, sponsored

#95 Fix: remove unnecessary logger import
  server/settings/conversion.py
Labels: type: bug

#92 Load Geo: Support loading all file formats `ReadGeo` supports, add `fbx`, `obj` and `usd` support
  client/ayon_nuke/plugins/load/load_model.py
Labels: type: enhancement, community

#94 Fix support for Optional state of `IncrementScriptVersion` from settings
  client/ayon_nuke/plugins/publish/increment_script_version.py
Labels: type: bug, community

#100 Chore: Fix missing space in error message
  client/ayon_nuke/api/lib.py
Labels: type: enhancement, community

#93 Load GeoImport/GeoReference: Add support for loading USD or Alembic using `GeoImport` and `GeoReference`
  client/ayon_nuke/plugins/load/load_usd.py
  server/settings/loader_plugins.py
Labels: type: enhancement, community
