Repository ynput/ayon-nuke, pull requests merged in 2025-07, with the labels that each got.

#124 Fix wrong frame being integrated as slate frame
  client/ayon_nuke/plugins/publish/collect_writes.py
Labels: type: bug

#125 AY-7997_Extract Render Local: Raise `PublishError` on render failure
  client/ayon_nuke/plugins/publish/extract_render_local.py
Labels: type: enhancement

#130 Load: Handles on version can be unset
  client/ayon_nuke/plugins/load/actions.py
  client/ayon_nuke/plugins/load/load_clip.py
Labels: type: bug, sponsored

#127 Create Backdrop: Remove `maintain_selection` attribute.
  client/ayon_nuke/plugins/create/create_backdrop.py
Labels: type: enhancement, community
