Repository ynput/ayon-nuke, pull requests merged in 2025-01, with the labels that each got.

#52 Fix use of stagingDir
  client/ayon_nuke/plugins/publish/collect_nuke_instance_data.py
  client/ayon_nuke/plugins/publish/extract_review_intermediates.py
  package.py
Labels: type: bug

#57 Update version constraints for core addon
  package.py
Labels: type: enhancement

#60 Fix returned colorspace list in `get_colorspace_list` - AY-7415
  client/ayon_nuke/api/colorspace.py
Labels: type: bug, sponsored
