Repository ynput/ayon-nuke, pull requests merged in 2025-02, with the labels that each got.

#61 Fix retime gathering from Nuke (freeze frame, linear speed and TimeWarp)
  client/ayon_nuke/plugins/load/load_clip.py
  package.py
  server/settings/loader_plugins.py
Labels: type: bug, sponsored

#65 Improve selection handling in NukeWriteCreator
  client/ayon_nuke/api/plugin.py
Labels: type: bug

#47 Easier `Gizmo Menu` settings
  client/ayon_nuke/api/lib.py
  server/settings/conversion.py
  server/settings/gizmo.py
Labels: type: enhancement

#79 Applying correctly viewer colorspace from settings
  client/ayon_nuke/api/colorspace.py
Labels: type: bug, sponsored

#77 Make ocioLook loader handle multiple chained LUTs.
  client/ayon_nuke/plugins/load/load_ociolook.py
Labels: type: enhancement, sponsored

#73 Chore: Remove 'six' usage
  client/ayon_nuke/api/lib.py
  client/ayon_nuke/api/plugin.py
  client/ayon_nuke/plugins/create/create_source.py
  client/ayon_nuke/plugins/load/load_effects.py
  client/ayon_nuke/plugins/load/load_effects_ip.py
  client/ayon_nuke/plugins/load/load_gizmo_ip.py
  client/ayon_nuke/plugins/load/load_ociolook.py
  client/ayon_nuke/plugins/publish/extract_slate_frame.py
  client/ayon_nuke/plugins/publish/validate_knobs.py
Labels: type: enhancement

#58 Replace render path in write nodes from stagingDir
  client/ayon_nuke/api/lib.py
  client/ayon_nuke/api/plugin.py
  client/ayon_nuke/plugins/publish/collect_writes.py
  client/ayon_nuke/plugins/publish/increment_write_node.py
  server/settings/publish_plugins.py
Labels: type: bug, sponsored
